
### Solicitar nuevo usuario
GET http://localhost:8080/api/users?page=1&limit=10


### Generacion de  nuevos usuario
GET http://localhost:8080/api/users/gen?userTotal=100


### Insertar nuevo usuario
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name":"Carlos Obando",
  "email": "carlos@gmail.com",
  "password":"1234567",
  "roll":"USER_ROLL",
  "google":true
}  

### Cambio de usuario
PUT http://localhost:8080/api/users/622fdce94620360a21059518
Content-Type: application/json

{
  "name": "Pedro Eduardo",
  "email": "pedroobando22@hotmail.com",
  "password":"1234567www",
  "roll":"USER_ROLE",
  "google":false
}

### Cambio de password usuario
PUT http://localhost:8080/api/users/password/623111aa9be5385ae2b87669
Content-Type: application/json

{
  "name": "Pedro Eduard2323232o",
  "email": "pedroobando22@hotmail.com",
  "password":"9999999",
  "roll":"USER_ROLE2323",
  "google":false
}

### Borrar usuario
DELETE http://localhost:8080/api/users/623111aa9be5385ae2b87669
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjMxMWVmZGYxZWRjYTMxOWE0MDY2Y2EiLCJpYXQiOjE2NDc0NDkyNzQsImV4cCI6MTY0NzQ3MDg3NH0.UZ04Kztktq-xzjP1zTCvaUUTHa1HGmPw5HWqEdoXJ1U

