
### Solicitar nuevo usuario
GET http://localhost:8080/api/users?page=2&orderby=desc

### Insertar nuevo usuario
POST http://localhost:8080/api/users
Content-Type: application/json

{
   "name": "pedro obando",
   "year": 51
}  

### Cambio de usuario
PUT http://localhost:8080/api/users/25?order=asc&total=sumatoriatotal
Content-Type: application/json

{
  "name": "Pedro Obando",
  "email": "pedroobando@hotmail.com"
}